# Generated by Django 5.0.3 on 2024-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_service_usage_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
